title: tulbo's page
url: https://tulboda.github.io
baseurl: /
author: Joseph
email: jsmolinelli@proton.me
description: my little room online

permalink: /blog/:title/

collections:
  garden:
    output: true
    permalink: /garden/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: garden
    values:
      layout: page
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed

feed:
  collections:
    - posts
