title: 난 털보다
url: https://tulbo.page
baseurl: /
author: Joseph
email: jsmolinelli@proton.me
description: my little room online

permalink: /blog/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed

feed:
  collections:
    - posts

exclude:
  - wrangler.toml
  - Gemfile
  - Gemfile.lock
  - vendor